#!/usr/bin/env python3
"""Create an isolated Hugging Face workspace for a LaughLM data-pipeline run.

The command creates only repositories explicitly requested with ``--apply``.
It reads the access token from an environment variable and never writes it to
the generated configuration or console output.
"""
from __future__ import annotations

import argparse
import copy
import os
import re
from pathlib import Path
from typing import Any

import yaml
from huggingface_hub import HfApi

from config_loader import DEFAULT_REGISTRY, load_yaml


DATASET_REPO_SUFFIXES = {
    "stage1": "stage1",
    "stage2": "stage2",
    "stage3": "stage3",
    "tokens": "tokens",
    "sealed_eval": "sealed-eval",
}
TOKENIZER_REPO_SUFFIX = "tokenizer"


def _slug(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9][^a-z0-9-]*", "-", value.lower()).strip("-")
    if not normalized:
        raise ValueError("profile must contain at least one letter or digit")
    return normalized


def _repo_id(namespace: str, prefix: str, suffix: str) -> str:
    return f"{namespace}/{prefix}-{suffix}"


def build_workspace(
    *,
    namespace: str,
    profile: str,
    registry: dict[str, Any],
) -> tuple[dict[str, Any], dict[str, str], str]:
    namespace = namespace.strip().strip("/")
    if not namespace or "/" in namespace:
        raise ValueError("namespace must be one Hugging Face user or organization name")
    prefix = f"laughlm-{_slug(profile)}"
    repos = {
        name: _repo_id(namespace, prefix, suffix)
        for name, suffix in DATASET_REPO_SUFFIXES.items()
    }
    tokenizer_repo = _repo_id(namespace, prefix, TOKENIZER_REPO_SUFFIX)

    generated = copy.deepcopy(registry)
    datasets = generated.get("datasets")
    if not isinstance(datasets, dict) or not datasets:
        raise ValueError("registry must contain a non-empty datasets mapping")
    for dataset in datasets.values():
        if not isinstance(dataset, dict):
            raise ValueError("registry dataset entries must be mappings")
        dataset["repos"] = {
            "stage1": repos["stage1"],
            "stage2": repos["stage2"],
            "stage3": repos["stage3"],
        }
    return generated, repos, tokenizer_repo


def _write_yaml(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(value, sort_keys=False), encoding="utf-8")


def _write_readme(
    path: Path,
    *,
    profile: str,
    repos: dict[str, str],
    tokenizer_repo: str,
) -> None:
    lines = [
        f"# LaughLM {profile} HF workspace",
        "",
        "This directory was generated by `bootstrap_hf_workspace.py`.",
        "It contains no Hugging Face access token.",
        "",
        "## Repositories",
        "",
    ]
    for name, repo_id in repos.items():
        lines.append(f"- `{name}`: `{repo_id}`")
    lines.extend([
        f"- `tokenizer` (model repo): `{tokenizer_repo}`",
        "",
        "Use `datasets.yaml` with `--registry` for Stage 1-3 commands.",
        "The sealed-eval repository must contain independently curated evaluation",
        "data and must never be added as a Stage-3/Stage-4 training source.",
    ])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--namespace", required=True, help="HF username or organization")
    parser.add_argument("--profile", default="smoke", help="Workspace label, e.g. smoke or production")
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--token-env", default="HF_TOKEN")
    parser.add_argument("--public", action="store_true", help="Create public instead of private repositories")
    parser.add_argument("--apply", action="store_true", help="Create missing HF repositories")
    parser.add_argument("--create-tokenizer-repo", action="store_true")
    args = parser.parse_args()

    profile = _slug(args.profile)
    output_dir = (args.output_dir or Path("configs/generated") / profile).expanduser().resolve()
    generated, repos, tokenizer_repo = build_workspace(
        namespace=args.namespace,
        profile=profile,
        registry=load_yaml(args.registry),
    )
    _write_yaml(output_dir / "datasets.yaml", generated)
    _write_readme(
        output_dir / "README.md",
        profile=profile,
        repos=repos,
        tokenizer_repo=tokenizer_repo,
    )

    print(f"[hf-bootstrap] generated registry: {output_dir / 'datasets.yaml'}")
    for name, repo_id in repos.items():
        print(f"[hf-bootstrap] {name}: {repo_id}")
    print(f"[hf-bootstrap] tokenizer: {tokenizer_repo}")

    if not args.apply:
        print("[hf-bootstrap] dry run: use --apply to create missing repositories")
        return

    token = os.environ.get(args.token_env)
    if not token:
        raise ValueError(f"Missing Hugging Face token in environment variable {args.token_env!r}")
    api = HfApi(token=token)
    for repo_id in repos.values():
        api.create_repo(
            repo_id=repo_id,
            repo_type="dataset",
            private=not args.public,
            exist_ok=True,
            token=token,
        )
        print(f"[hf-bootstrap] ready dataset repo: {repo_id}")
    if args.create_tokenizer_repo:
        api.create_repo(
            repo_id=tokenizer_repo,
            repo_type="model",
            private=not args.public,
            exist_ok=True,
            token=token,
        )
        print(f"[hf-bootstrap] ready model repo: {tokenizer_repo}")


if __name__ == "__main__":
    main()
